### PR TITLE
fixes for v0.7

### PR DESCRIPTION
**Pull request by jonathanBieler**
Hi, @timholy I'm trying to update this to v0.7, and it works for the most part but I'm getting stuck with the iteration/List in `compose.jl`, since the iteration interface has changed and I don't really understand what the purpose of that part I could use some hints.

### CODE REVIEW

**Comment by timholy** [comment]
Seems like it's there to iterate over a list but return items transformed by `native`, perhaps to convert to some kind of absolute coordinate system. (Probably needed in hit-testing.) But it's been a *long* time and I have not either looked at this or followed Compose, so there's not much more help I can provide.

**Comment by jonathanBieler** [comment]
@timholy I've fixed the remaining issues, I just had to disable the face test because of [this](https://github.com/fhs/ZipFile.jl/issues/14), but otherwise everything seems to work.

**Comment by timholy** [comment]
This all looks fine to me, thanks for doing it! Merge at will.

**Comment by jonathanBieler** [comment]
Thanks!

**Pull request merged**
